# Site settings
title: Hexiang Hu
description: "A simple site for Hexiang's public announcements, tech/non-tech posts and personal updates"
background: /images/background/background-cube.jpg
deep_background: /images/background/background-deepcube-2.jpg

baseurl: ""
# the subpath of your site, e.g. /blog/
url: "https://hexiang-hu.github.io"
# the base hostname & protocol for your sit

# Pagination≈ì
paginate: 10
paginate_path: "/posts/page/:num/"

# Build settings
markdown: kramdown

# permalink setting
permalink: pretty
# highlighter: rouge
highlighter: pygments

# Social media link for the site
social:
  twitter:    Hexiang_Hu
  github:     Hexiang-Hu
  facebook:   Hu.Hexiang
  linkedin:   hexianghu
  rss:        /feed.xml

# customized document resources
collections:
  toys:
    output: true

scss:
  sass_dir: _scss
  style: :compressed

gems: 
  ['jekyll-paginate', 'jekyll/scholar']