# Site settings
title: Hexiang Hu
description: "A simple site for Hexiang's public announcements, tech/non-tech posts and personal updates"
background: /images/background/background-cube.jpg
deep_background: /images/background/background-deepcube-2.jpg

# Site user settings
user:
  name:       "Hexiang(Frank) Hu"
  title:      "student [at] Simon Fraser University"
  email:      "hexiang_hu [at] sfu.ca"
  head_pic:   /images/self-portrait/me.jpg
  deep_pic:   /images/self-portrait/deep-me.jpg
  desc:
    title:    "In Deep."
    content:  "I am passionte with Deep Learning as well as Computer Vision. My research interest majorly focuses on <em class='text-grey-bright'>Structured Visual Recognition with Deep Learning</em>."

baseurl: ""
# the subpath of your site, e.g. /blog/
url: "https://hexiang-hu.github.io"
# the base hostname & protocol for your sit

# Pagination
paginate: 10
paginate_path: "/posts/page/:num/"

# Social media link for the site
social:
  twitter:    Hexiang_Hu
  github:     Hexiang-Hu
  facebook:   Hu.Hexiang
  linkedin:   hexianghu
  rss:        /feed.xml


# Build settings
markdown: kramdown

# permalink setting
permalink: pretty
highlighter: rouge

# customized document resources
collections:
  toys:
    output: true

scss:
  sass_dir: _scss
  style: :compressed

gems: 
  ['jekyll-paginate', 'jekyll/scholar']