# Site settings
title: Ape's Banana Tree
description: A simple site for Hexiang's public announcements, tech/non-tech posts and personal updates
background: images/background-cube.jpg

user:
    name: Hexiang Hu
    title: Undergraduate at Simon Fraser University
    email: hexianghu@sfu.ca
    head_pic: images/me.jpg

# config variable for enabling comments
# comments: true

# this means to ignore newlines until "baseurl:"
# Write an awesome description for your new site here. You can edit this
# line in _config.yml. It will appear in your document head meta (for
# Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://Hex-iang.github.io" # the base hostname & protocol for your site
social:
    twitter: Hexiang_Hu
    github:  Hex-iang
    facebook: Hu.Hexiang
    linkedin: hexianghu
# Build settings
markdown: kramdown


scss:
  sass_dir: _scss
  style: :compressed
