# Site settings
title: Banana Tree
description: A simple site for Hexiang's public announcements, tech/non-tech posts and personal updates
background: /images/background/background-cube.jpg
deep_background: /images/background/background-deepcube.jpg

# Site user settings
user:
    name:       "Hexiang Hu"
    title:      "[at] Simon Fraser University"
    email:      "hexiang_hu [at] sfu.ca"
    head_pic:   /images/self-portrait/me.jpg
    deep_pic:   /images/self-portrait/deep-me.jpg

baseurl: ""
# the subpath of your site, e.g. /blog/
url: "https://hex-iang.github.io"
# the base hostname & protocol for your sit

# Pagination
paginate: 4
paginate_path: "/page:num/"

# Social media link for the site
social:
    twitter:    Hexiang_Hu
    github:     Hex-iang
    facebook:   Hu.Hexiang
    linkedin:   hexianghu
    rss:        /feed.xml


# Build settings
markdown: kramdown

# permalink setting
permalink: pretty

# customized document resources
collections:
    toys:
        output: true

scss:
  sass_dir: _scss
  style: :compressed
